[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
base-sepolia = "https://sepolia.base.org"
optimism-sepolia = "https://sepolia.optimism.io"
celo-alfajores = "https://alfajores-forno.celo-testnet.org"
mode-sepolia = "https://sepolia.mode.network"

[etherscan]
celo-alfajores = { key = "${CELOSCAN_API_KEY}" }
base-sepolia = { key = "${BASESCAN_API_KEY}" }
optimism-sepolia = { key = "${OPTIMISM_API_KEY}" }
mode-sepolia = { key = "${MODE_API_KEY}" }
